#!/usr/bin/env bash
#script that will display information about subdomains

dom="$1"

if [ "$#" -eq 2 ]
then
    subdom="$2"
else
    subdom=("www" "lb-01" "web-01" "web-02")
fi

for i in "${subdom[@]}"

do
    echo -n "The subdomain $i"
    dig "$i.$dom" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{print " is a " $4 " record and points to " $5}'

done


