#!/usr/bin/env bash
#Tranfers a file

if [ "$#" -le 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o 'StrictHostKeyChecking=no' -i ubuntu@34.74.218.90:~/
fi
