#!/usr/bin/env bash
#Run Nginx as Nginx
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
pkill -f apache2
sudo -u nginx service nginx start
